name: Update Sing-box Adblock Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天更新一次
  workflow_dispatch:  # 支持手动触发

jobs:
  update_adblock_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Sing-box
      run: |
        curl -fsSL https://sing-box.app/install.sh | sh

    - name: Create rules directory
      run: |
        mkdir -p rules

    - name: Download adblock rule files
      run: |
        curl -o adguard-sdnsfilter.txt https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
        curl -o ppfeufer-blocklist.txt https://raw.githubusercontent.com/ppfeufer/adguard-filter-list/master/blocklist

    - name: Convert adblock rules to binary format
      run: |
        sing-box rule-set convert --type adguard --output rules/adguard-sdnsfilter.srs adguard-sdnsfilter.txt
        sing-box rule-set convert --type adguard --output rules/ppfeufer-blocklist.srs ppfeufer-blocklist.txt

    - name: Commit & Push SRS files
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        git add rules/*.srs
        git commit -m "Auto update adblock rules" || echo "No changes"
        git push
